/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        bg: "#0A0A0A",
        surface: "#141414",
        "surface-elevated": "#1E1E1E",
        "surface-overlay": "#282828",
        card: "#1A1A1A",
        border: "#1F1F1F",
        "border-active": "#333333",
        divider: "#1A1A1A",
        "divider-strong": "#252525",
        "text-primary": "#F5F5F5",
        "text-secondary": "#999999",
        "text-tertiary": "#555555",
        ghost: "#3A3A3A",
        primary: "#E94560",
        "primary-muted": "#E9456020",
        secondary: "#4ECDC4",
        "secondary-muted": "#4ECDC420",
        tertiary: "#A855F7",
        "tertiary-muted": "#A855F720",
        success: "#4ADE80",
        "success-muted": "#4ADE8020",
        warning: "#FBBF24",
        "warning-muted": "#FBBF2420",
        error: "#EF4444",
        "error-muted": "#EF444420",
        "pr-gold": "#FFD700",
        "rpe-7": "#4ECDC4",
        "rpe-8": "#FBBF24",
        "rpe-9": "#F97316",
        "rpe-10": "#E94560",
        "phase-intro": "#4ECDC4",
        "phase-base": "#E94560",
        "phase-deload": "#FBBF24",
        "phase-intensification": "#A855F7",
      },
      fontFamily: {
        sans: ["Inter"],
        mono: ["JetBrainsMono"],
      },
    },
  },
  plugins: [],
};
